import {Simulation,places,distance,clamp} from './simulation.js';
import {Campaign} from './campaign.js';
import {ExpandedWorld} from './expanded-world.js';
import {locations,regions,roadSegments,vehicleTypes,weapons,regionAt,waterAt} from './content.js';
const $=id=>document.getElementById(id),sim=new Campaign();let world,started=false,last=0,yaw=Math.PI,pitch=.15,stick={x:0,y:0},drag=null,muted=false,audio=null,engine=null,engineGain=null,toastTime=0,hudTime=0,failedShown=false;
const keys=new Set();$('startBtn').disabled=true;
const debug={sichtbar:false,frames:0,fps:0,fenster:0,zeit:0};
// setPointerCapture wirft, wenn der Zeiger zwischen Ereignis und Handler
// schon losgelassen wurde. Das darf die Eingabe nicht abbrechen.
const fange=(el,id)=>{try{el.setPointerCapture(id);}catch{}};
window.LOWTIDE={sim,get world(){return world;},get frames(){return debug.frames;},debug,
 // Nur fürs Prüfen: setzt Figur und Kamera an eine feste Stelle.
 // hoehe>0 pausiert die Simulation und hebt die Kamera für Übersichtsbilder an.
 view(x,z,blick=yaw,neigung=pitch,hoehe=0){const p=sim.player;p.car=null;p.x=x;p.z=z;p.y=hoehe;p.vy=0;
  yaw=blick;pitch=neigung;p.yaw=blick;sim.paused=hoehe>0;if(world){world.freieKamera=false;world.nebelFaktor=1;world.kameraSofort=true;}},
 // Freie Kamera für Luftbilder: Standort, Blickziel, Simulation läuft weiter.
 luftbild(x,y,z,zx,zy,zz){if(!world)return;world.freieKamera=true;world.nebelFaktor=.06;
  world.camera.position.set(x,y,z);world.camera.lookAt(zx,zy,zz);
  world.camera.far=2600;world.camera.updateProjectionMatrix();
  sim.player.x=x;sim.player.z=z;}};
try{let saved=null;try{saved=localStorage.getItem('lowtide-v2');}catch{}if(saved){try{sim.restore(JSON.parse(saved));}catch(e){console.warn('Spielstand konnte nicht geladen werden',e);}}world=new ExpandedWorld($('game'),sim);$('loadState').textContent='Port Mercy ist bereit.';$('startBtn').disabled=false;}catch(error){$('loadState').textContent='3D konnte nicht starten. Verwende einen Browser mit WebGL 2 (Safari, Chrome oder Firefox).';console.error(error);}
function initAudio(){try{audio=new (window.AudioContext||window.webkitAudioContext)();engine=audio.createOscillator();engine.type='sawtooth';engineGain=audio.createGain();engineGain.gain.value=0;engine.connect(engineGain).connect(audio.destination);engine.start();}catch{muted=true;}}
function tone(freq,duration,volume=.04,type='sine'){if(!audio||muted)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(30,freq*.4),audio.currentTime+duration);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}
function toast(message){$('toast').textContent=message;$('toast').style.opacity='1';toastTime=5;}
function dialog(speaker,title,text,choices){sim.paused=true;keys.clear();stick={x:0,y:0};$('speaker').textContent=speaker;$('dialogTitle').textContent=title;$('dialogText').textContent=text;$('choices').replaceChildren();for(const [label,fn] of choices){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{$('dialog').close();sim.paused=false;fn();};$('choices').append(b);}$('dialog').showModal();}
function interact(){const a=sim.action();if(a?.startsWith('place:')){showPlace(a.split(':')[1]);return;}if(a==='chapter2'){dialog('MARA QUINN','Ein zweiter Name.','Die Ratsakte führt zu Nadia, einer Zeugin auf Isla Serena. Mara muss zuerst das Relais abschalten, Eli kann danach mit seiner Karte ins Stadtarchiv. Wache und Kamera reagieren auf auffälliges Verhalten.',[['Auftrag annehmen',()=>{sim.campaign.stage=1;toast('Tab / Figuren: Wechsel zu Mara. Relais auf der Karte.');}],['Später',()=>{}]]);return;}if(a==='finale'){dialog('ELI & MARA','Alles auf den Tisch.','Nadia ist sicher. Ihr habt nun die vollständige Akte. Veröffentlichung beendet Calderas Einfluss; ein Deal kauft euch Freiheit und lässt die Verantwortlichen davonkommen.',[['Alles veröffentlichen',()=>{sim.campaign.stage=4;sim.relationship=Math.min(100,sim.relationship+20);sim.award(1800);saveGame();toast('Port Mercy kennt die Wahrheit. Kampagne abgeschlossen.');}],['Einen Deal schließen',()=>{sim.campaign.stage=4;sim.relationship=Math.max(0,sim.relationship-25);sim.award(3000);saveGame();toast('Der Deal ist durch. Kampagne abgeschlossen.');}]]);return;}if(a==='mara')dialog('MARA QUINN','Ein einfacher Auftrag.','Caldera schickt nachts Tanker ohne Ladungspapiere raus. Im Lager liegt eine Festplatte. Hol sie mir. Du kannst den Wachmann bezahlen, die Sicherung an der Ostwand ziehen oder den Eingang aufbrechen.',['accept'].map(()=>['Ich hole die Festplatte.',()=>sim.choose('accept')]).concat([['Noch nicht.',()=>{}]]));if(a==='guard')dialog('CALDERA · NACHTWACHE','Hier gibt es nichts zu sehen.','Der Wachmann mustert dich. Hinter ihm läuft eine Überwachungskamera. An der rechten Außenwand findest du den Stromkasten.',[['$150 anbieten — der Wachmann lässt dich durch',()=>sim.choose('bribe')],['Schloss aufbrechen — löst Alarm aus',()=>sim.choose('force')],['Zurück. Ich suche die Sicherung.',()=>{}]]);if(a==='ending')dialog('MARA QUINN','Was soll mit der Wahrheit passieren?','Die Daten belegen: Caldera verklappt Chemikalien vor der Küste. Ein Stadtrat kassiert mit. Mara will die Beweise veröffentlichen. Caldera bietet dir Geld fürs Schweigen.',[['Veröffentlichen · $800 · Maras Vertrauen',()=>finish('leak')],['An Caldera verkaufen · $2.000 · Mara verlieren',()=>finish('sell')]]);}
function finish(choice){sim.choose(choice);dialog('AUFTRAG ABGESCHLOSSEN',choice==='leak'?'Die Flut bringt alles zurück.':'Der Preis des Schweigens.',choice==='leak'?'Die Presse veröffentlicht die Dokumente. Der Hafen steht still. Mara schickt dir eine Nachricht: „Das war erst der Anfang.“ Du kannst Port Mercy weiter erkunden.':'Caldera überweist das Geld. Maras Nummer ist nicht mehr erreichbar. Draußen am Hafen gehen die Lichter wieder an. Du kannst Port Mercy weiter erkunden.',[['Zurück in die Stadt',()=>{}],['Nächster Auftrag',()=>{sim.campaign.stage=1;toast('Mara muss das Relais abschalten. Tab / Figuren zum Wechseln.');}]]);}
function fire(){if(sim.paused)return;const before=sim.shots;sim.shoot();if(sim.shots>before)tone(125,.14,.11,'sawtooth');}
function pause(){if(!started||$('dialog').open||$('bigMap').open)return;sim.paused=true;keys.clear();stick={x:0,y:0};$('pause').showModal();}
function resume(){if(sim.player.health<=0)return;$('pause').close();sim.paused=false;}
function map(){if(!started||$('dialog').open||$('pause').open)return;sim.paused=true;keys.clear();drawMap($('fullMap'),true);$('bigMap').showModal();}
function keyAction(key){if(!started)return;if(key==='escape'){if($('pause').open)resume();else pause();return;}if(sim.paused)return;if(key==='e')interact();if(key==='q'){if(!sim.player.car){sim.player.armed=!sim.player.armed;tone(320,.06);}}if(key==='r')sim.reload();if(key==='fire')fire();if(key==='m')map();if(key==='tab'){sim.switchCharacter();yaw=sim.player.yaw;}if(key==='x')sim.cycleWeapon();if(key==='f')sim.melee();if(key==='g')sim.grapple();if(key==='v')sim.cover();if(key==='alt')sim.dodge();if(key===' '&&!sim.player.car)sim.jump();if(key==='h')showActions();if(key==='f3'){debug.sichtbar=!debug.sichtbar;$('debug').hidden=!debug.sichtbar;}}
$('startBtn').onclick=()=>{started=true;sim.paused=false;document.body.classList.add('playing');initAudio();toast('Sprich mit Mara am goldenen Marker. E / Aktion.');};$('pauseBtn').onclick=pause;$('resume').onclick=resume;$('restartBtn').onclick=()=>{$('pause').close();dialog('SPIELSTAND','Neu beginnen?','Dadurch wird der lokale Spielstand gelöscht.',[['Neues Spiel',()=>{localStorage.removeItem('lowtide-v2');location.reload();}],['Abbrechen',()=>{}]]);};$('mapBtn').onclick=map;$('closeMap').onclick=()=>{$('bigMap').close();sim.paused=false;};$('soundBtn').onclick=()=>{muted=!muted;$('soundBtn').textContent='Ton: '+(muted?'aus':'an');};let low=false;$('qualityBtn').onclick=()=>{low=!low;world.renderer.setPixelRatio(low?1:Math.min(devicePixelRatio,1.5));world.renderer.shadowMap.enabled=!low;world.resize();$('qualityBtn').textContent='Grafik: '+(low?'sparsam':'normal');};
for(const id of ['dialog','pause','bigMap'])$(id).addEventListener('cancel',e=>{e.preventDefault();if(id==='pause')resume();else if(id==='bigMap'){$(id).close();sim.paused=false;}});
window.addEventListener('keydown',e=>{if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab','F3','Escape'].includes(e.key))e.preventDefault();const k=e.key.toLowerCase();if(!e.repeat)keyAction(k);keys.add(k);});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();stick={x:0,y:0};if(started&&!sim.paused)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&started&&!sim.paused)pause();});window.addEventListener('resize',()=>world?.resize());
$('game').addEventListener('contextmenu',e=>e.preventDefault());$('game').addEventListener('pointerdown',e=>{if(!started||sim.paused)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,time:performance.now()};fange($('game'),e.pointerId);});$('game').addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;yaw-=(e.clientX-drag.x)*.006;pitch=clamp(pitch+(e.clientY-drag.y)*.003,-.2,.8);drag.x=e.clientX;drag.y=e.clientY;});$('game').addEventListener('pointerup',e=>{if(drag&&Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)<6&&performance.now()-drag.time<300)fire();drag=null;});$('game').addEventListener('pointercancel',()=>drag=null);
let stickId=null;function moveStick(e){const r=$('stick').getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,len=Math.max(40,Math.hypot(x,y));stick={x:x/len,y:y/len};$('knob').style.transform=`translate(${stick.x*34}px,${stick.y*34}px)`;}$('stick').onpointerdown=e=>{stickId=e.pointerId;fange($('stick'),e.pointerId);moveStick(e);};$('stick').onpointermove=e=>{if(e.pointerId===stickId)moveStick(e);};const releaseStick=()=>{stickId=null;stick={x:0,y:0};$('knob').style.transform='';};$('stick').onpointerup=releaseStick;$('stick').onpointercancel=releaseStick;for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{e.preventDefault();fange(b,e.pointerId);const key=b.dataset.key;keys.add(key);keyAction(key);};b.onpointerup=()=>keys.delete(b.dataset.key);b.onpointercancel=()=>keys.delete(b.dataset.key);}
function drawMap(canvas,full=false){const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,p=sim.player;ctx.fillStyle='#203630';ctx.fillRect(0,0,w,h);const scale=full?w/1080:1.1,cx=full?-90:p.x,cz=full?-40:p.z,tx=x=>w/2+(x-cx)*scale,tz=z=>h/2+(z-cz)*scale;ctx.fillStyle='#284f56';ctx.fillRect(tx(119),0,w,h);ctx.fillRect(tx(-545),tz(-20),145*scale,150*scale);ctx.fillStyle='#7c9275';ctx.fillRect(tx(235),tz(150),125*scale,145*scale);ctx.fillStyle='#687372';for(const r of roadSegments)ctx.fillRect(tx(Math.min(r.x1,r.x2)-r.w/2),tz(Math.min(r.z1,r.z2)-r.w/2),Math.max(r.w,Math.abs(r.x2-r.x1))*scale,Math.max(r.w,Math.abs(r.z2-r.z1))*scale);ctx.fillStyle='#9a9f8c';for(const b of sim.solids)ctx.fillRect(tx(b.x-b.w/2),tz(b.z-b.d/2),b.w*scale,b.d*scale);function dot(x,z,r,color){ctx.beginPath();ctx.arc(tx(x),tz(z),r,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}if(sim.lastSeen){ctx.beginPath();ctx.arc(tx(sim.lastSeen.x),tz(sim.lastSeen.z),35*scale,0,Math.PI*2);ctx.fillStyle='#d9768144';ctx.fill();}for(const c of sim.cars)dot(c.x,c.z,full?2:2.5,'#83abbe');for(const c of sim.cops)if(c.active)dot(c.x,c.z,3,'#ef7b76');if(full){ctx.font='bold 11px Arial';for(const r of regions){ctx.fillStyle='#d7d7b4';ctx.fillText(r.name,tx(r.x)-20,tz(r.z)-14);}ctx.font='10px Arial';for(const [id,l]of Object.entries(locations)){dot(l.x,l.z,3,'#91d9bb');ctx.fillStyle='#cee0cd';ctx.fillText(l.name,tx(l.x)+5,tz(l.z));}}const goal=sim.objective();dot(goal.x,goal.z,5,'#efca88');const other=sim.characters[1-sim.active];dot(other.x,other.z,4,'#c3a5d8');ctx.save();ctx.translate(tx(p.x),tz(p.z));ctx.rotate(-p.yaw);ctx.beginPath();ctx.moveTo(0,7);ctx.lineTo(-5,-5);ctx.lineTo(0,-2);ctx.lineTo(5,-5);ctx.closePath();ctx.fillStyle='#a2f0db';ctx.fill();ctx.restore();ctx.fillStyle='#d0dcd1';ctx.font='12px Arial';ctx.fillText('N',w-18,18);}
function updateHUD(){const p=sim.player;$('clock').textContent=String(Math.floor(sim.hour)).padStart(2,'0')+':'+String(Math.floor(sim.hour%1*60)).padStart(2,'0')+' · '+({clear:'Klar',rain:'Regen',fog:'Nebel',storm:'Gewitter'}[sim.weather]);$('district').textContent=regionAt(p);$('actor').textContent=p.name;$('stars').textContent='★'.repeat(sim.stars)+'☆'.repeat(6-sim.stars);$('police').textContent=sim.stars?(sim.spotted?'Sichtkontakt':'Suche · '+Math.floor(sim.unseen)+' s außer Sicht'):'Keine Fahndung';$('health').style.width=p.health+'%';$('money').textContent='$ '+p.money.toLocaleString('de-DE');$('equipment').textContent=p.car?vehicleTypes[p.car.model].name+' · '+Math.ceil(p.car.health)+'% · Tank '+Math.ceil(p.car.fuel)+'%':p.armed?weapons[p.weapon].name+' · '+p.ammo+' / '+p.reserve:p.cover?'In Deckung':p.sneak?'Schleichend':'Ausdauer '+Math.round(p.stamina)+'%';$('speed').textContent=p.car?Math.round(Math.abs(p.car.speed)*3.6)+' km/h'+(p.car.alt>2?' · '+Math.round(p.car.alt)+' m':''):p.y<-.5?'Luft '+Math.round(p.air)+'%':'';$('reticle').style.display=p.armed?'block':'none';$('goal').textContent=sim.missionTitle();$('subgoal').textContent=sim.stars?'Verliere Sichtkontakt und verlasse das Suchgebiet.':sim.campaign.stage?'Goldener Marker auf der Karte · Tab / Figuren zum Wechseln':sim.mission===4?'Mara am Bootshaus oder direkt den nächsten Auftrag starten.':'E / Aktion am goldenen Marker';$('chapter').textContent=sim.campaign.stage?'02–03 / DIE RATS AKTE'.replace('RATS AKTE','RATSAKTE'):'01 / DIE SCHWARZE FLUT';let prompt='';if(sim.unlock)prompt='E / Aktion halten · '+Math.ceil(sim.unlock.remaining)+' s';else if(sim.activity)prompt=sim.activity.kind==='race'?'Kontrollpunkt '+(sim.activity.index+1)+' / '+sim.activity.points.length:sim.activity.kind==='diving'?'C halten: tauchen · E beim Wrackfund':'E / Aktion im richtigen Moment';else if(p.car)prompt='E aussteigen · H / Mehr für Werkstatt & Aktivitäten';else{const l=Object.values(locations).find(l=>distance(l,p)<4.5);if(l)prompt='E / Aktion · '+l.name;else if(distance(p,sim.objective())<5)prompt='E / Aktion · Missionsziel';else if(sim.cars.some(c=>distance(c,p)<5&&c.health>0))prompt='E / Aktion · Einsteigen (bei Schloss halten)';}$('prompt').textContent=prompt;const a=sim.activity;$('activityHud').hidden=!a;if(a){$('activityName').textContent=a.label;$('activityPointer').style.left=((a.phase||0)*100)+'%';$('activityScore').textContent=a.kind==='race'?a.time.toFixed(1)+' s':a.kind==='fishing'?(a.time>=a.biteAt?'BISS! JETZT DRÜCKEN':'Warte auf den Biss …'):a.kind==='diving'?'Zum Wrack schwimmen und abtauchen':(a.score||0)+' Treffer / '+(a.round||0)+' Versuche';$('timingBar').hidden=['race','diving','fishing'].includes(a.kind);}drawMap($('map'));}
function messwerte(dt){debug.frames++;debug.fenster++;debug.zeit+=dt;if(debug.zeit>=.5){debug.fps=debug.fenster/debug.zeit;debug.fenster=0;debug.zeit=0;}if(!debug.sichtbar||!world)return;const info=world.renderer.info;
 $('debug').textContent=['FPS          '+debug.fps.toFixed(0),'Draw Calls   '+info.render.calls,'Dreiecke     '+info.render.triangles.toLocaleString('de-DE'),'Geometrien   '+info.memory.geometries,'Texturen     '+info.memory.textures,'NPCs         '+sim.npcs.length,'Fahrzeuge    '+sim.cars.length,'Polizei aktiv '+sim.cops.filter(c=>c.active).length,'Uhrzeit      '+sim.hour.toFixed(2),'Wetter       '+sim.weather,'Position     '+Math.round(sim.player.x)+' / '+Math.round(sim.player.z)].join('\n');}
function frame(ms){const dt=Math.min(.05,(ms-last)/1000||.016);last=ms;messwerte(dt);if(world){if(started&&!sim.paused){if(keys.has('arrowleft'))yaw+=dt*1.8;if(keys.has('arrowright'))yaw-=dt*1.8;const forward=(keys.has('w')||keys.has('arrowup')?1:0)-(keys.has('s')||keys.has('arrowdown')?1:0)-stick.y,turn=(keys.has('d')?1:0)-(keys.has('a')?1:0)+stick.x;sim.tick(dt,{forward:clamp(forward,-1,1),turn:clamp(turn,-1,1),yaw,sprint:keys.has('shift'),sneak:keys.has('c'),brake:keys.has(' '),jump:keys.has(' '),interact:keys.has('e')});if(sim.player.car&&!drag)yaw+=Math.atan2(Math.sin(sim.player.yaw-yaw),Math.cos(sim.player.yaw-yaw))*Math.min(1,dt*3);if(keys.has('fire'))fire();if(engineGain){engineGain.gain.setTargetAtTime(!muted&&sim.player.car?.health>0?.017:0,audio.currentTime,.1);engine.frequency.setTargetAtTime((vehicleTypes[sim.player.car?.model]?.sound||45)+Math.abs(sim.player.car?.speed||0)*3,audio.currentTime,.1);}}else if(engineGain)engineGain.gain.setTargetAtTime(0,audio.currentTime,.1);world.update(dt,yaw,pitch,started);if(sim.events.length)toast(sim.events.pop()),sim.events.length=0;toastTime-=dt;if(toastTime<=0)$('toast').style.opacity='0';hudTime-=dt;if(hudTime<=0){updateHUD();hudTime=.12;}if(sim.player.health<=0&&!failedShown){failedShown=true;dialog('PORT MERCY POLICE','Festgenommen.','Der Auftrag ist gescheitert. Verliere beim nächsten Versuch zuerst den Sichtkontakt, wechsle bei Bedarf das Fahrzeug und verlasse das markierte Suchgebiet.',[['An der Klinik weiterspielen',()=>{const p=sim.player;p.health=100;p.money=Math.max(0,p.money-100);p.x=locations.clinic.x;p.z=locations.clinic.z+7;p.y=0;p.car=null;sim.stars=0;sim.heat=0;sim.lastSeen=null;sim.description=null;sim.activity=null;failedShown=false;saveGame();}]]);}}requestAnimationFrame(frame);}requestAnimationFrame(frame);

function saveGame(){try{localStorage.setItem('lowtide-v2',JSON.stringify(sim.snapshot()));toast('Spielstand gespeichert.');}catch(e){toast('Spielstand konnte auf diesem Gerät nicht gespeichert werden.');}}
function showPlace(id){const l=locations[id];sim.serviceLocation=id;const buy=(label,item)=>[label,()=>{sim.buy(item);saveGame();}];let options=[];
 if(id==='garage')options=[buy('Reparatur · $150','car:repair'),buy('Lack wechseln · $120','car:paint'),buy('Motor-Upgrade · $400 (max. 3)','car:engine'),buy('Sportreifen · $100','car:tires'),buy('Fahrwerk · $100','car:suspension'),buy('Felgen · $100','car:rims'),buy('Auspuff · $100','car:exhaust'),buy('Innenraum · $100','car:interior'),buy('Beleuchtung · $100','car:lights'),buy('Karosserie-Kit · $100','car:body')];
 if(id==='shop')options=[buy('Karabiner · $650','weapon:rifle'),buy('Schrotflinte · $500','weapon:shotgun'),buy('Taser · $180','weapon:taser'),buy('Munition · $60','ammo'),buy('Kleidung · $80','clothes'),buy('Haarschnitt · $35','hair'),buy('Tattoo · $90','tattoo')];
 if(id==='clinic')options=[buy('Behandlung · $50','heal')];if(id==='diner')options=[buy('Essen & Erholung · $18','food')];if(id==='fuel')options=[buy('Volltanken · $35','fuel')];if(id==='home')options=[buy('Sechs Stunden ausruhen','rest'),['Spiel speichern',saveGame]];if(id==='motel')options=[buy('Ausruhen · $60 / als Eigentümer gratis','rest'),buy('Zimmer dauerhaft erwerben · $900','motel')];
 if(['court','gym','fish','club','dive','race','skydive'].includes(id))options=[[id==='race'?'Rennen starten (im Fahrzeug)':'Aktivität starten',()=>sim.startActivity(l.kind)]];
 if(!options.length)options=[['Zurück in die Welt',()=>{}]];options.push(['Schließen',()=>{}]);dialog(l.name.toUpperCase(),l.name,id==='garage'?'Bring dein Fahrzeug bis an die offene Werkstatt. Käufe verändern dieses Fahrzeug.':id==='shop'?'Waffenwechsel: X. Geld und Inventar gehören der aktiven Figur.':'Erkunde Solvara. Dein Fortschritt wird auf diesem Gerät gespeichert.',options);}
function showActions(){dialog('LOWTIDE','Aktionen',sim.player.name+' · Vertrauen '+sim.relationship+'/100',[[sim.characters[1-sim.active].name+' übernehmen',()=>{sim.switchCharacter();yaw=sim.player.yaw;}],['Waffe wechseln',()=>sim.cycleWeapon()],['Nachladen',()=>sim.reload()],['Nahkampf / leiser Takedown',()=>sim.melee()],['Gegner festsetzen',()=>sim.grapple()],['Deckung',()=>sim.cover()],['Ausweichen',()=>sim.dodge()],['Rennen starten (beim West Loop)',()=>{if(distance(sim.player,locations.race)<12)sim.startActivity('race');else toast('Fahre zum West Loop: Marker auf der Karte.');}],['Aktivität abbrechen',()=>sim.cancelActivity()],['Spiel speichern',saveGame],['Zurück',()=>{}]]);}
$('moreBtn').onclick=showActions;$('switchBtn').onclick=()=>{if(!sim.paused){sim.switchCharacter();yaw=sim.player.yaw;}};$('saveBtn').onclick=saveGame;$('activityTap').onclick=()=>sim.activity?.kind==='diving'?sim.action():sim.activityTap();$('activityCancel').onclick=()=>sim.cancelActivity();
let saveCounter=0;setInterval(()=>{if(started&&!sim.paused&&sim.player.health>0){try{localStorage.setItem('lowtide-v2',JSON.stringify(sim.snapshot()));}catch{}}},15000);
